# ------------------------------------------------------------------------------
# Prepare npm repo
# ------------------------------------------------------------------------------

before_script:
  - cp "$NPMRC" $HOME/.npmrc

# ------------------------------------------------------------------------------
# Common stages
# ------------------------------------------------------------------------------

stages:
  - install
  - build
  - test
  - docs
  - publish
  - analysis

# ------------------------------------------------------------------------------
# Docker image to run the different stages
# ------------------------------------------------------------------------------

image: node:16

# ------------------------------------------------------------------------------
# Pipeline
# ------------------------------------------------------------------------------

install:
  stage: install
  script:
    - node -v; npm -v
    - npm ci --prefer-offline audit=false
  artifacts:
    paths:
      - node_modules/
  interruptible: true

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  interruptible: true

test:jest:
  stage: test
  needs: ['install']
  script:
     - npm test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  interruptible: true

test:eslint:
  stage: test
  needs: ['install']
  script:
    - npm run lint
  interruptible: true

pages:
  stage: docs
  script:
    - npm run docs
    - mv docs public
  artifacts:
    paths:
      - public/
  when: manual
  allow_failure: true
  interruptible: true

publish:
  stage: publish
  script:
    - npm publish dist/
  rules:
    - if: $CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?([-]((alpha|beta)[.])?[0-9]+)?$/

# ------------------------------------------------------------------------------
# Code and vulnerability analysis
# ------------------------------------------------------------------------------

snyk:
  dependencies: []
  cache: []
  needs: []
  stage: analysis
  image: snyk/snyk-cli:npm
  before_script:
    - cp "$NPMRC" $HOME/.npmrc
    - snyk auth ${SNYK_TOKEN}
  script:
    - snyk test --severity-threshold=low
  after_script:
    - snyk monitor --org="serviceops" --all-projects